# Generated by Django 5.0.3 on 2026-03-31 19:41

import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('embedding', pgvector.django.VectorField(dimensions=384)),
            ],
        ),
    ]
